spring.application.name=playlist-api
spring.datasource.url=jdbc:mysql://localhost:3306/playlistdb
spring.datasource.username=root
spring.datasource.password=12VBDXMnw_&Hem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true